(() => {
  "use strict";

  window.HPGB_CONFIG = {
    BANK_SHORT_NAME: "HPGB",
    BANK_NAME: "Himachal Pradesh Gramin Bank",
    APP_NAME: "HPGBmBanking",
    APP_NAME_SUP: "Plus",
    APP_TITLE: "HPGB mBanking",
    APP_SUBTITLE: "Secure mobile access",
    TOLL_FREE: "1800-180-7777",
    SUPPORT_EMAIL: "contacthpgb@hpgb.bank.in",
    START_APPLICATION_URL: "https://www.hpgb.bank.in/customer",
    PRIVACY_POLICY_URL: "https://hpgbmobile.in",
    LOCATE_BRANCH_URL: "https://www.hpgb.bank.in/nearest-branch",
    WHATSAPP_BANKING_NUMBER: "919212361889",
    HOLIDAYS_LIST_URL: "https://hpgb.bank.in/holidays",
    TERMS_URL: "https://hpgb.bank.in",
    FORM_26AS_URL: "https://services.tdscpc.gov.in/serv/tapn/welcome26AS.xhtml",
    BBPS_COMPLAINT_URL: "https://www.bharat-connect.com/support/raise-complaint-customer/",
    WHATSAPP_BASE_URL: "https://wa.me/",
    SOCIAL_FACEBOOK_HANDLE: "hpgbank",
    SOCIAL_X_HANDLE: "hpgbank",
    SOCIAL_INSTAGRAM_HANDLE: "hpgbank",
    SOCIAL_YOUTUBE_HANDLE: "hpgbank",
    SOCIAL_FACEBOOK_BASE_URL: "https://facebook.com/",
    SOCIAL_X_BASE_URL: "https://x.com/",
    SOCIAL_INSTAGRAM_BASE_URL: "https://instagram.com/",
    SOCIAL_YOUTUBE_BASE_URL: "https://youtube.com/@",
    HOME_SECTIONS: [
      {
        title: "My Account",
        items: [
          { label: "Account View", icon: "account_balance", route: { path: "/account-view" } },
          { label: "Account Statement", icon: "description", route: { path: "/account-statement" } },
          { label: "Year Wise Statement", icon: "event", route: { path: "/year-wise-statement" } },
          { label: "mPassbook", icon: "menu_book", route: { path: "/mpassbook" } },
        ],
      },
      {
        title: "Fund Transfer",
        items: [
          {
            label: "Own Accounts",
            icon: "swap_horiz",
            route: { path: "/initiatetransfer", query: { type: "own" } },
          },
          {
            label: "Send to Beneficiary",
            icon: "person_add",
            route: { path: "/initiatetransfer", query: { type: "beneficiary" } },
          },
          { label: "Quick Pay", icon: "bolt", route: { path: "/quickpay" } },
          {
            label: "Beneficiary Management",
            icon: "groups",
            route: { path: "/beneficiaries" },
          },
        ],
      },
      {
        title: "Bill Payment",
        items: [
          { label: "Bharat Bill Pay", icon: "receipt_long", route: { path: "/bbps" } },
          { label: "Mobile Recharge", icon: "smartphone", route: { path: "/mobile-recharge" } },
          { label: "DTH Recharge", icon: "tv", route: { path: "/dth-recharge" } },
          { label: "Bill Payment", icon: "credit_card", route: { path: "/bill-payment" } },
        ],
      },
      {
        title: "Card Management",
        items: [
          { label: "Hostlist Debit Card", icon: "block", route: { path: "/hostlist-debit-card" } },
          { label: "Generate Green PIN", icon: "pin", route: { path: "/generate-green-pin" } },
          { label: "Card Management", icon: "credit_card", route: { path: "/card-management" } },
          { label: "Limit Management", icon: "tune", route: { path: "/limit-management" } },
        ],
      },
      {
        title: "Deposit Management",
        more: "More",
        moreRoute: { path: "/deposit-management" },
        items: [
          { label: "Open FD", icon: "savings", route: { path: "/open-fd" } },
          { label: "Open RD", icon: "show_chart", route: { path: "/open-rd" } },
          { label: "FD Closure", icon: "lock", route: { path: "/fd-closure" } },
          { label: "Track FD Status", icon: "timeline", route: { path: "/track-fd-status" } },
        ],
      },
      {
        title: "Social Security Scheme",
        items: [
          { label: "PMJJBY", icon: "shield", route: { path: "/pmjjby" } },
          { label: "PMSBY", icon: "verified_user", route: { path: "/pmsby" } },
          { label: "APY", icon: "verified", route: { path: "/apy" } },
        ],
      },
      {
        title: "Cheques Management",
        items: [
          { label: "Inquire Cheque", icon: "search", route: { path: "/inquire-cheque" } },
          { label: "Stop Cheque", icon: "stop_circle", route: { path: "/stop-cheque" } },
          { label: "View Cheque", icon: "visibility", route: { path: "/view-cheque" } },
          { label: "PPS", icon: "receipt", route: { path: "/pps" } },
        ],
      },
      {
        title: "Other Services",
        items: [
          { label: "Limit Management", icon: "tune", route: { path: "/limit-management" } },
          { label: "Form 15G/H", icon: "description", route: { path: "/form-15gh" } },
          { label: "Form 26 AS", icon: "article", route: { path: "/form-26as" } },
          { label: "CKYC", icon: "verified_user", route: { path: "/ckyc" } },
        ],
      },
    ],
    DEPOSIT_ACTIONS: [
      {
        title: "Open FD",
        subtitle: "Create a fixed deposit in minutes with instant confirmation.",
        icon: "savings",
        pill: "New deposit",
        route: { path: "/open-fd" },
      },
      {
        title: "Open RD",
        subtitle: "Start a recurring deposit with flexible tenure options.",
        icon: "show_chart",
        pill: "New deposit",
        route: { path: "/open-rd" },
      },
      {
        title: "FD Closure",
        subtitle: "Close an existing fixed deposit securely.",
        icon: "lock",
        pill: "Manage",
        route: { path: "/fd-closure" },
      },
      {
        title: "Track FD Status",
        subtitle: "Review fixed deposit request progress in real time.",
        icon: "timeline",
        pill: "Status",
        route: { path: "/track-fd-status" },
      },
      {
        title: "Track RD Status",
        subtitle: "Monitor recurring deposit requests and installments.",
        icon: "query_stats",
        pill: "Status",
        route: { path: "/track-rd-status" },
      },
    ],
    TRANSFER_TRANSACTION_TYPES: [
      { label: "IMPS", value: "IMPS" },
      { label: "NEFT", value: "NEFT" },
      { label: "Within Bank", value: "Within Bank" },
      { label: "Self", value: "Self" },
    ],
    ACCOUNT_VIEW_TABS: [
      { label: "SAVINGS", value: "savings" },
      { label: "CURRENT", value: "current" },
      { label: "OVERDRAFT", value: "overdraft" },
      { label: "TERM DEPOSIT", value: "term-deposit" },
      { label: "LOAN", value: "loan" },
    ],
    LIMIT_MANAGEMENT_ITEMS: [
      { label: "Update ATM Limit", route: { path: "/limit-atm" } },
      { label: "Update POS Limit", route: { path: "/limit-pos" } },
      { label: "Update EComm Limit", route: { path: "/limit-ecomm" } },
      { label: "Update Contactless Limit", route: { path: "/limit-contactless" } },
    ],
    LIMIT_STANDARD_LIMITS: {
      atm: "25,000.00",
      pos: "60,000.00",
      ecomm: "60,000.00",
      contactless: "2,000.00",
    },
    FD_TYPES: ["Normal", "Tax Saver"],
    FD_TYPE_TAX_SAVER: "Tax Saver",
    FD_RATES: {
      Normal: 7.15,
      "Tax Saver": 7.2,
    },
    FD_PARTIAL_WITHDRAWALS: ["No"],
    FD_MATURITY_INSTRUCTIONS_DEFAULT: ["Auto Renew", "Auto Close"],
    FD_MATURITY_INSTRUCTIONS_TAX_SAVER: ["Auto Close"],
    FD_MATURITY_INSTRUCTION_AUTO_CLOSE: "Auto Close",
    FD_TAX_SAVER_TENURE_YEARS: "5",
    FD_TAX_SAVER_TENURE_MONTHS: "0",
    FD_TAX_SAVER_TENURE_DAYS: "0",
    FD_NOMINEE_OPTIONS: ["Yes", "No"],
    FD_INTEREST_OPTIONS: ["On Maturity", "Monthly/Quarterly"],
    FD_CLOSURE_BASE_RATE: 7.25,
    FD_STATUS_INTEREST_RATE: "7.25",
    RD_NOMINEE_OPTIONS: ["Yes", "No"],
    RD_SCHEDULE_OPTIONS: ["No", "Yes"],
    RD_PAYMENT_DATES: Array.from({ length: 31 }, (_, index) => String(index + 1)),
    RD_INTEREST_RATE_LABEL: "Int. Rate: 7.05",
    FD_STATUS_DETAIL: {
      transactionId: "",
      status: "",
      scheme: "FDMB",
      amount: "0.00",
      durationYears: "1",
      durationMonths: "0",
      durationDays: "0",
      openDate: "",
      customerName: "",
      depositAccount: "",
      maturityAmount: "0.00",
      maturityDate: "",
      debitAccount: "",
      nomineeRetain: "Yes",
      maturityInstruction: "Redeem",
    },
    RD_STATUS_DETAIL: {
      transactionId: "",
      status: "",
      scheme: "RD Flexi",
      installmentAmount: "0.00",
      tenureYears: "1",
      tenureMonths: "0",
      openDate: "",
      customerName: "",
      depositAccount: "",
      maturityAmount: "0.00",
      maturityDate: "",
      debitAccount: "",
      interestRate: "6.85",
      nomineeRetain: "Yes",
      maturityInstruction: "Credit to savings",
    },
    MINI_STATEMENT_TYPE_MAP: [
      { key: "current", match: "current" },
      { key: "overdraft", match: "overdraft" },
      { key: "term-deposit", match: "term" },
      { key: "loan", match: "loan" },
    ],
    MINI_STATEMENT_DEFAULT_TYPE: "savings",
    COMPOUNDING_MAP: {
      monthly: 12,
      quarterly: 4,
      halfyearly: 2,
      yearly: 1,
    },
  };
})();
